SET DEFINE OFF;

-- HIS Staff Domain (Oracle)
-- 목적: 관리자가 병원 직원을 등록·관리 (회원가입/자가가입 아님)
-- Tables: HIS_DEPT_MST, HIS_STAFF_MST
-- 관리자가 직원 등록 시 초기 비밀번호(STAFF_PASSWORD)도 함께 지정
-- Run as hp user after his_common_domain.sql (HIS_ROLE required for FK)
-- Example:
--   sqlplus hp/7777@localhost:1521/XE "@database/oracle/his_staff.sql"

BEGIN EXECUTE IMMEDIATE 'DROP TABLE HIS_STAFF_MST CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HIS_DEPT_MST CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
-- 구버전 테이블명 정리 (이전 스크립트 실행 이력 대비)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HIS_STAFF CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HIS_DEPARTMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

-- ---------------------------------------------------------------------------
-- HIS_DEPT_MST : 부서 마스터
-- ---------------------------------------------------------------------------
CREATE TABLE HIS_DEPT_MST (
    DEPARTMENT_ID      VARCHAR2(20)    NOT NULL,
    DEPARTMENT_NAME    VARCHAR2(100)   NOT NULL,
    DEPARTMENT_NAME_EN VARCHAR2(100),
    USE_YN             CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_AT         TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_HIS_DEPT_MST PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT CK_HIS_DEPT_MST_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

COMMENT ON TABLE HIS_DEPT_MST IS '부서 마스터';

-- ---------------------------------------------------------------------------
-- HIS_STAFF_MST : 직원 등록 마스터 (인사 + 로그인 계정)
-- 관리자 화면(/staff)에서 직원 정보·초기 비밀번호를 등록하는 용도
-- ---------------------------------------------------------------------------
CREATE TABLE HIS_STAFF_MST (
    STAFF_ID              VARCHAR2(20)    NOT NULL,
    STAFF_PASSWORD        VARCHAR2(255)   NOT NULL,
    STAFF_NAME            VARCHAR2(50)    NOT NULL,
    STAFF_TYPE            VARCHAR2(10)    NOT NULL,
    STAFF_ROLE_CODE       VARCHAR2(20)    NOT NULL,
    STAFF_DEPARTMENT_ID   VARCHAR2(20)    NOT NULL,
    STAFF_RANK_CODE       VARCHAR2(10)    NOT NULL,
    STAFF_POSITION_CODE   VARCHAR2(10),
    STAFF_PHONE           VARCHAR2(20)    NOT NULL,
    STAFF_EXTENSION_NO    VARCHAR2(10),
    STAFF_EMAIL           VARCHAR2(100),
    STAFF_HIRE_DATE       DATE            NOT NULL,
    STAFF_STATUS          VARCHAR2(10)    DEFAULT 'ACTIVE' NOT NULL,
    STAFF_BIRTH_DATE      DATE            NOT NULL,
    STAFF_LICENSE_NO      VARCHAR2(50),
    CREATED_BY            VARCHAR2(20),
    UPDATED_BY            VARCHAR2(20),
    CREATED_AT            TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_HIS_STAFF_MST PRIMARY KEY (STAFF_ID),
    CONSTRAINT FK_HIS_STAFF_MST_DEPT FOREIGN KEY (STAFF_DEPARTMENT_ID)
        REFERENCES HIS_DEPT_MST (DEPARTMENT_ID),
    CONSTRAINT FK_HIS_STAFF_MST_ROLE FOREIGN KEY (STAFF_ROLE_CODE)
        REFERENCES HIS_ROLE (ROLE_CODE),
    CONSTRAINT CK_HIS_STAFF_MST_TYPE CHECK (STAFF_TYPE IN ('DOC', 'NUR', 'ADM')),
    CONSTRAINT CK_HIS_STAFF_MST_STATUS CHECK (STAFF_STATUS IN ('ACTIVE', 'LEAVE', 'RETIRED'))
);

COMMENT ON TABLE HIS_STAFF_MST IS '직원 등록 마스터 (관리자 등록, 인사+계정)';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_ID IS '직원 ID (사번, PK, 로그인 ID)';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_PASSWORD IS '초기 비밀번호 (관리자 등록 시 지정, BCrypt 등 암호화 저장)';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_NAME IS '직원 이름';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_TYPE IS '직군: DOC(의사), NUR(간호사), ADM(행정)';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_ROLE_CODE IS '시스템 권한 코드 (HIS_ROLE.ROLE_CODE)';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_DEPARTMENT_ID IS '소속 부서 ID';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_RANK_CODE IS '직급 코드 (과장, 대리, 주임, 원장 등)';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_POSITION_CODE IS '직책 코드 (센터장, 파트장, 팀장 등)';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_PHONE IS '전화번호';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_EXTENSION_NO IS '내선번호';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_EMAIL IS '이메일';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_HIRE_DATE IS '입사일';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_STATUS IS '재직상태: ACTIVE(재직), LEAVE(휴직), RETIRED(퇴직)';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_BIRTH_DATE IS '생년월일';
COMMENT ON COLUMN HIS_STAFF_MST.STAFF_LICENSE_NO IS '면허 번호 (의사/간호사)';
COMMENT ON COLUMN HIS_STAFF_MST.CREATED_BY IS '등록 처리한 관리자 ID';
COMMENT ON COLUMN HIS_STAFF_MST.UPDATED_BY IS '최종 수정한 관리자 ID';

CREATE INDEX IDX_HIS_STAFF_MST_DEPT ON HIS_STAFF_MST (STAFF_DEPARTMENT_ID);
CREATE INDEX IDX_HIS_STAFF_MST_ROLE ON HIS_STAFF_MST (STAFF_ROLE_CODE);
CREATE INDEX IDX_HIS_STAFF_MST_STATUS ON HIS_STAFF_MST (STAFF_STATUS);
CREATE INDEX IDX_HIS_STAFF_MST_TYPE ON HIS_STAFF_MST (STAFF_TYPE);

-- ---------------------------------------------------------------------------
-- Sample Data (개발용)
-- STAFF_PASSWORD: BCrypt hash of "1111"
-- $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
-- ---------------------------------------------------------------------------
INSERT INTO HIS_DEPT_MST (DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_EN)
VALUES ('DEPT_IM', UNISTR('\B0B4\C6D0'), 'Internal Medicine');
INSERT INTO HIS_DEPT_MST (DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_EN)
VALUES ('DEPT_NS', UNISTR('\AC04\D638\BD80'), 'Nursing');
INSERT INTO HIS_DEPT_MST (DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_EN)
VALUES ('DEPT_ADM', UNISTR('\D589\C815\BD80'), 'Administration');

INSERT INTO HIS_STAFF_MST (
    STAFF_ID, STAFF_PASSWORD, STAFF_NAME, STAFF_TYPE, STAFF_ROLE_CODE,
    STAFF_DEPARTMENT_ID, STAFF_RANK_CODE, STAFF_POSITION_CODE,
    STAFF_PHONE, STAFF_EXTENSION_NO, STAFF_EMAIL,
    STAFF_HIRE_DATE, STAFF_STATUS, STAFF_BIRTH_DATE, STAFF_LICENSE_NO,
    CREATED_BY
) VALUES (
    'S2026001',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
    UNISTR('\D64D\AE38\C6D0'),
    'DOC', 'ROLE_DOCTOR',
    'DEPT_IM', 'CHIEF', 'CENTER_HEAD',
    '010-1234-5678', '2101', 'doctor@hospital.com',
    DATE '2026-03-02', 'ACTIVE', DATE '1995-05-12', 'DOC-123456',
    'ADMIN'
);

INSERT INTO HIS_STAFF_MST (
    STAFF_ID, STAFF_PASSWORD, STAFF_NAME, STAFF_TYPE, STAFF_ROLE_CODE,
    STAFF_DEPARTMENT_ID, STAFF_RANK_CODE,
    STAFF_PHONE, STAFF_EMAIL,
    STAFF_HIRE_DATE, STAFF_STATUS, STAFF_BIRTH_DATE,
    CREATED_BY
) VALUES (
    'S2026002',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
    UNISTR('\AE40\AC04\D638'),
    'NUR', 'ROLE_NURSE',
    'DEPT_NS', 'STAFF',
    '010-2345-6789', 'nurse@hospital.com',
    DATE '2025-11-01', 'ACTIVE', DATE '1998-08-20',
    'ADMIN'
);

COMMIT;
EXIT;
