SET PAGESIZE 100
SET LINESIZE 200

SELECT 'HIS_DEPT_MST=' || COUNT(*) FROM HIS_DEPT_MST;
SELECT 'HIS_STAFF_MST=' || COUNT(*) FROM HIS_STAFF_MST;

SELECT STAFF_ID, STAFF_NAME, STAFF_TYPE, STAFF_ROLE_CODE,
       STAFF_DEPARTMENT_ID, STAFF_RANK_CODE, STAFF_STATUS
  FROM HIS_STAFF_MST
 ORDER BY STAFF_ID;

EXIT;
